spring:
  application:
    name: code-flux
  config:
    import: optional:file:./config/config.yaml,optional:file:../config/config.yaml,optional:file:${APP_CONFIG_FILE:../config/config.yaml}
  main:
    banner-mode: off

server:
  port: ${SERVER_PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  version: ${APP_VERSION:0.1.0}
